version: '3.1'

services:
  url-shortener-server:
    container_name: url-shortener-server
    build:
      context: ../../../../.
      dockerfile: Dockerfile.dev
    ports:
      - '8088:8088'
    depends_on:
      - mongo

  mongo:
    container_name: url-shortener-mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
