version: '3.1'

services:
  mongo:
    container_name: url-shortener-mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  url-shortener-server:
    container_name: url-shortener-server
    build:
      context: ../../../../.
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: mongodb://localhost:27017/url_shortener
    links:
      - mongo