version: '3.1'

services:
  url-shortener-server:
    container_name: url-shortener-server
    build:
      context: ../../../../.
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - mongo-db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_HOST: mongo-db

  mongo-db:
    container_name: url-shortener-mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example